spring:
  server:
    port: 48620
  config:
    import: optional:application-secrets.yml
  datasource:
    url: jdbc:mysql://i12d109.p.ssafy.io:13790/reper?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: jeongeoneya0831!
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update # (개발환경) -> (운영 환경) validation/none
    datasource:
      initialization-mode: always
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  elasticsearch:
    uris: http://i12d109.p.ssafy.io:23159  # (보안 적용될땐 https로 바꾸기)
    socket-timeout: 60s
    username: ""  # 보안 비활성화에선 빈 값
    password: ""
    ssl:
      enabled: false
    repositories:
      enabled: false
#    username: elastic
#    password: ${ELASTIC_PASSWORD}
#    index:
#      auto-create-index: false
#      ca-certificate: classpath:docker/certs/ca.crt
#      key: classpath:certs/elasticsearch.key
#      certificate: classpath:certs/elasticsearch.crt

firebase:
  credential: ${FIREBASE_JSON}  # 🔥 환경 변수에서 Firebase JSON을 가져오기

logging.level:
  org.hibernate.SQL: debug # (개발 환경) SQL 로그 출력
  org.hibernate.orm.jdbc.bind: trace # (개발 환경) SQL 바인딩 값 출력

springdoc.override-with-generic-response: false

kakao:
  client_id: 11a435ceceba6f2724e9f7b1b9b69f5b
  redirect_uri: http://i12d109.p.ssafy.io:13790/api/auth/callback


